accounts/urls.py
from django.urls import path

from serializers import views as apiviews
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('users/', apiviews.UserList.as_view()),
    path('users/<int:pk>', apiviews.UserDetail.as_view()),
]

articles/urls.py
from django.contrib import admin
from django.urls import path

from serializers.views import ArticleList
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.article_list, name='list'),
    path('create/', views.article_create, name='create'),
    path('<int:pk>/', views.article_details, name='article_detail'),
    path('articlelist/', ArticleList.as_view()),
]

twitter/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from articles import views as article_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', article_views.article_list, name='home'),
    path('article/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='assets/default.png', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.username} Profile'

articles/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.


class Article(models.Model):
    title = models.CharField(max_length=500)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='blogs.jpg', blank=True)
    author = models.ForeignKey(User, default=None, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50]+'...'

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from accounts.models import Profile


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

articles/forms.py
from django import forms
from . import models


class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title', 'slug', 'body', 'thumb']

accounts/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout, authenticate


# Create your views here.
from accounts.forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm
from accounts.models import Profile


def signup_view(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            # log the uer in
            return redirect('articles:list')
    else:
        form = UserRegisterForm()
    return render(request, 'accounts/signup.html', {'form':form})


@login_required
def profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST,
                                   request.FILES,
                                   instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            return redirect('accounts:profile')

    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form
    }

    return render(request, 'accounts/profile.html', context)


@receiver(post_save, sender=User)
def create_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_profile(sender, instance, **kwargs):
    instance.profile.save()


def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            return redirect('articles:list')

    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form':form})


def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('articles:list')

articles/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

# Create your views here.
from articles import forms

from articles.models import Article
from rest_framework.response import Response


def article_list(request):
    articles = Article.objects.all().order_by('date')

    return render(request, 'articles/article_list.html', {'articles': articles})


def article_details(request, pk):
    article = Article.objects.get(pk=pk)
    return render(request, 'articles/article_detail.html', {'article': article})


@login_required(login_url="/accounts/login/")
def article_create(request):
    if request.method == 'POST':
        form = forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            # save
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('articles:list')
    else:
        form = forms.CreateArticle()
    return render(request, 'articles/article_create.html', {'form':form})

serializers/views.py
from django.shortcuts import render

# Create your views here.
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
from rest_framework import status, generics, viewsets
from rest_framework.decorators import action
from rest_framework.response import Response
from rest_framework.utils import json
from rest_framework.views import APIView

from articles.models import Article
from .serializers import UserSerializer, ArticleSerializer


class UserView(APIView):
    model = User

    def get(self,request):
        user = User.objects.all()
        serializer = UserSerializer(user, many=True)
        return Response(serializer.data)


class ArticleList(APIView):

    def get(self,request):
        article = Article.objects.all()
        serializer = ArticleSerializer(article, many=True)
        return Response(serializer.data)

    def post(self, request):
        serializer = ArticleSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)

    def perform_create(self, serializer):
        serializer.save(owner=self.request.user)


class UserList(generics.ListAPIView):
    queryset = User.objects.all()
    serializer_class = UserSerializer


class UserDetail(generics.RetrieveAPIView):
    queryset = User.objects.all()
    serializer_class = UserSerializer

templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
<h1>Login</h1>
<form class="site-form" action="{% url 'accounts:login' %}" method="post">
    {% csrf_token %}
    {{ form }}

    {% if request.GET.next %}
        <input type="hidden" name="next" value="{{ request.GET.next }}">
    {% endif %}
    <input type="submit" value="login">
</form>
{% endblock %}

templates/accounts/profile.html
{% extends 'base.html' %}

{% block content %}
<div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
        <div class="media-body">
          <h2 class="account-heading">{{ user.username }}</h2>
          <p class="text-secondary">{{ user.email }}</p>
        </div>
      </div>
    <form method="POST" enctype="multipart/form-data" class="site-form">
          {% csrf_token %}
              {{ u_form }}
              {{ p_form }}
        <button class="btn btn-outline-info" type="submit" value="update_profile">Update</button>
    </form>

      <!-- FORM HERE -->
</div>
{% endblock %}

templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
<h1>Signup</h1>
<form class="site-form" action="/accounts/signup/" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="signup">
</form>
{% endblock %}

templates/articles/article_create.html
{% extends 'base.html' %}

{% block content %}
    <div class="create-article">
        <h2>create</h2>
        <form class="site-form" action="{% url 'articles:create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="create">
        </form>
    </div>
    <script src="/static/slugify.js"></script>

{% endblock %}

templates/articles/article_detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="article-detail">
        <div class="article">
            <center>
            <img src="{{ article.thumb.url }}">
            </center>
            <h2>{{ article.title }}</h2>
            <p>{{ article.body }}</p>
            <p>{{ article.date }}</p>
        </div>
    </div>
{% endblock %}

templates/articles/article_list.html
{% extends 'base.html' %}

{% block content %}
    <h1> Article List</h1>
    <div class="articles">
        {% for article in articles %}
            <div class="article">
                <h2><a href="{% url 'articles:article_detail' pk=article.pk %}">{{ article.title }}</a></h2>
                <p> {{ article.snippet }}</p>
                <p> {{ article.date }}</p>
                <p class="author">added by {{ article.author.username }}</p>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/base.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <title>Articles</title>
</head>

<body>
    <div class="wrapper">
        <h1><a href="{% url 'home' %}"><img src="{% static 'blogs.jpg' %}" style="height:30px;"></a></h1>
        <nav>
            <ul>
                {% if user.is_authenticated %}
                <li>
                    <form class="" action="{% url 'accounts:logout' %}" method="post">
                        {% csrf_token %}
                        <button type=submit">Logout</button>
                    </form>
                </li>
                <li><a href="{% url 'articles:create' %}" class="highlight">New Article</a></li>
                {% else %}
                <li><a href="{% url 'accounts:login' %}">Login</a></li>
                <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
                {% endif %}
            </ul>
        </nav>
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

templates/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Homepage</title>
</head>
<body>
<h1>
    This is the homepage
</h1>
<p>
    hi
</p>
</body>
</html>

templates/post_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    hi there

</body>
</html>